on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["stable", "current"]
        racket-variant: ["BC", "CS"]
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v0.12
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing reprovide-lang and its dependencies
        run: raco pkg install --no-docs --auto ./reprovide-lang-lib ./reprovide-lang
      - name: Compiling reprovide-lang and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps reprovide
      - name: Testing reprovide-lang
        run: raco test -p reprovide-lang-lib reprovide-lang
